### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s3-evaluacion-intermedia-japocoinyenhoang#1]
Forget about the extra components. Follow the exercise guide and solve it in the App.js file.
Here you have some tips to solve it:

- [x] Remember that the `.map()` method only applies to arrays.
- [x] Trak your props: If you name a prop as `paquito` you should retrieve it inside the component using the same name `this.props.paquito``

Once you solve it only using the App.js component you can commit your changes and create the other exercise components.

This time you have a deadline: 16-1-2019.

You can do it!!

**Comment by japocoinyenhoang** [comment]
Hi Carlos, 
Sorry for not finished the exercises in time.  It was the first thing i did after luch this afternoon, but i didn't merge it with master without your aproval. It is in a brach called continueathome. And it runs properly, i think. 
I know that map() is only for arrays, but i was in a hurry.
Thanks for checking my exercises, and tell me the errors and how to fix them.

**Comment by japocoinyenhoang** [comment]
sorry, the branch is completeathome istead of continueathome.

Have a nice day, and thanks again.

**Comment by japocoinyenhoang** [comment]
I also did another brach called whitoutstate using this.props. (my intention was called it whitoutstate, but my messy fingers just change the possitions of the letters).
so please, can you check it too and thell me if i can improve it anyway.
thanks.

**Comment by oneeyedman** [comment]
Hi, @japocoinyenhoang. Well done. Just solve these two little items and merge it to master:
- [ ] Install node-sass using the --save flag so that a simple `$ npm install` would install all the dependencies needed to run the project.
- [ ] Publish on Github Pages

**Comment by japocoinyenhoang** [comment]
Hi @oneeyedman.

I think i did what you ask me to do.

Have a nice day.

**Comment by japocoinyenhoang** [comment]
Cleanning Up your GitHub issues?
